
INSERT INTO public.problem_solutions (problem_number, symptom, category, recommended_products, display_order) VALUES
(1, 'Voiture consomme trop de carburant', 'carburant', 'Traitement essence ou diesel + Full métal', 1),
(2, 'Moteur manque de puissance', 'moteur', 'Nettoyant injecteurs, nettoyant admission', 2),
(3, 'Démarrage difficile', 'moteur', 'Départ moteur', 3),
(4, 'Ralenti instable', 'moteur', 'Nettoyant injecteurs', 4),
(5, 'Moteur qui broute', 'moteur', 'Nettoyant injecteurs', 5),
(6, 'Fumée noire à l''échappement', 'echappement', 'Service nettoyage complet 360° sans démontage', 6),
(7, 'Fumée blanche', 'echappement', 'Nettoyant injecteurs', 7),
(8, 'Fumée bleue', 'echappement', 'Anti-usure + Stop fuite moteur', 8),
(9, 'Moteur diesel encrassé', 'moteur', 'Décalaminant moteur 5 en 1 diesel', 9),
(10, 'Consommation d''huile élevée', 'moteur', 'Plasma LXR - Full métal - Octane booster', 10),
(11, 'Surchauffe moteur', 'refroidissement', 'Nettoyant radiateur + Stop fuite radiateur', 11),
(12, 'Radiateur bouché', 'refroidissement', 'Nettoyant radiateur', 12),
(13, 'Fuite radiateur', 'refroidissement', 'Stop fuite radiateur', 13),
(14, 'Liquide de refroidissement sale', 'refroidissement', 'Nettoyant détartrant radiateur + Liquide de refroidissement', 14),
(15, 'Ralenti instable (carburant)', 'carburant', 'Traitement carburant essence ou diesel', 15),
(16, 'Climatisation mauvaise odeur', 'habitacle', 'Purifiant habitacle + Filtre à air', 16),
(17, 'Air de climatisation sale', 'habitacle', 'Désinfectant climatisation + Filtre à air', 17),
(18, 'Habitacle qui sent mauvais', 'habitacle', 'Purifiant habitacle + Filtre à air', 18),
(19, 'Plastiques ternes', 'habitacle', 'Rénovateur plastique', 19),
(20, 'Tableau de bord sale', 'habitacle', 'Nettoyant habitacle', 20),
(21, 'Vitres sales', 'habitacle', 'Nettoyant vitres', 21),
(22, 'Voiture qui tremble', 'moteur', 'Nettoyant injecteurs', 22),
(23, 'Boîte de vitesse dure', 'transmission', 'ATF Flush + Huile boîte', 23),
(24, 'Bruits métalliques moteur (disparaissent à chaud)', 'moteur', 'Poussoir hydraulique + Octane booster (essence)', 24),
(25, 'Moteur bruyant au ralenti', 'moteur', 'Poussoir hydraulique', 25),
(26, 'Perte compression moteur', 'moteur', 'Maxi compression', 26),
(27, 'Injection sale', 'carburant', 'Nettoyant injecteurs', 27),
(28, 'Turbo encrassé', 'moteur', 'Service nettoyage turbo 360° sans démontage', 28),
(29, 'Vanne EGR encrassée', 'moteur', 'Kit Nettoyant EGR', 29),
(30, 'Admission sale', 'moteur', 'Traitement diesel + Service nettoyage circuit admission 360° sans démontage', 30),
(31, 'Consommation carburant élevée en ville', 'carburant', 'Nettoyant injecteurs', 31),
(32, 'Moteur diesel fume', 'echappement', 'Nettoyant injecteurs diesel + Traitement diesel', 32),
(33, 'Moteur essence encrassé', 'moteur', 'Décalaminant moteur 5 en 1 essence', 33),
(34, 'Carburant de mauvaise qualité', 'carburant', 'Traitement essence ou diesel + Octane booster (essence)', 34),
(35, 'Soupçon d''eau dans le diesel', 'carburant', 'Traitement essence ou diesel + Dispersant d''eau', 35),
(36, 'Voiture lente à accélérer', 'moteur', 'Nettoyant injecteurs', 36),
(37, 'Moteur qui cale', 'moteur', 'Nettoyant injecteurs', 37),
(38, 'Odeur carburant', 'carburant', 'Nettoyant injecteurs', 38),
(39, 'Surchauffe moteur (complète)', 'refroidissement', 'Nettoyant radiateur + Stop fuite radiateur + Liquide de refroidissement + Huile moteur + Filtre + Nettoyant prévidange', 39),
(40, 'Surchauffe moteur (refroidissement)', 'refroidissement', 'Nettoyant radiateur + Stop fuite radiateur + Liquide de refroidissement', 40),
(41, 'Direction bruyante', 'direction', 'HFS Hydraulic fluid + Stop fuite direction assistée', 41),
(42, 'Freins bruyants', 'freinage', 'Dégraissant frein', 42),
(43, 'Disques encrassés', 'freinage', 'Dégraissant frein + Méca clean 5L usage professionnel', 43),
(44, 'Contacts électriques oxydés', 'electrique', 'Nettoyant contact électrique', 44),
(45, 'Connecteurs sales', 'electrique', 'Nettoyant contact', 45),
(46, 'Condenseur sale', 'habitacle', 'Purifiant + Désinfectant habitacle', 46),
(47, 'Injecteurs partiellement bouchés', 'carburant', 'Nettoyant injecteurs', 47),
(48, 'Huile moteur trop sale, filtre colmaté', 'moteur', 'Nettoyant prévidange + Huile moteur + Filtre', 48),
(49, 'Moteur manque de reprise', 'moteur', 'Nettoyant injecteurs', 49),
(50, 'Entretien préventif moteur', 'moteur', 'Full métal - Anti usure - Plasma LXR', 50);
